/**
 * Case Studies motion contract.
 *
 * Shared overview timings are sourced from the Atlas overview interaction
 * vocabulary. Case Studies keeps only motion that is specific to entering and
 * exiting the Case Studies system plus its own breath staggering.
 */

import {
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY,
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION,
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION,
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY,
  ATLAS_OVERVIEW_READING_HANDOFF_DURATION,
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION,
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION,
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION,
  ATLAS_OVERVIEW_RETURN_DURATION,
  ATLAS_OVERVIEW_SELECTION_EASE,
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION,
} from "../overview/atlasOverviewMotion";

export const CASE_STUDIES_ENTRY_DURATION = 900;
export const CASE_STUDIES_EXIT_DURATION = 820;
export const CASE_STUDIES_PULL_EASE = ATLAS_OVERVIEW_SELECTION_EASE;

export const SELECTION_PULSE_DURATION =
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION;
export const DRAWER_CLOSE_DURATION =
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION;
export const DRAWER_OPEN_DURATION =
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION;
export const OVERVIEW_LABEL_REVEAL_DELAY =
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY;
export const OVERVIEW_CHROME_REVEAL_DELAY =
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY;

export const REDUCED_MOTION_TRANSITION_DURATION =
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION;
export const REDUCED_MOTION_DRAWER_DURATION =
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION;

export const PROJECT_READING_HANDOFF_DURATION =
  ATLAS_OVERVIEW_READING_HANDOFF_DURATION;
export const PROJECT_READING_REDUCED_HANDOFF_DURATION =
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION;

export const PROJECT_RETURN_DURATION =
  ATLAS_OVERVIEW_RETURN_DURATION;
export const PROJECT_RETURN_REDUCED_DURATION =
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION;

export const PROJECT_BREATH_DELAYS = [0, 0.8, 1.5, 2.2] as const;
