/**
 * Frameworks overview motion contract.
 *
 * Shared overview timings are sourced from the Atlas overview interaction
 * vocabulary. Frameworks keeps geometry transitions and breath staggering
 * local because those are part of its spatial expression.
 */

import {
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY,
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION,
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION,
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY,
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION,
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION,
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION,
  ATLAS_OVERVIEW_RETURN_DURATION,
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION,
} from "../overview/atlasOverviewMotion";
import {
  ATLAS_SYSTEM_ACKNOWLEDGE_DELAY,
  ATLAS_SYSTEM_ENTRY_DURATION,
  ATLAS_SYSTEM_EXIT_DURATION,
  ATLAS_SYSTEM_PULL_EASE,
  ATLAS_SYSTEM_RESOLVE_DURATION,
  ATLAS_SYSTEM_RESOLVE_START,
} from "../overview/atlasSystemTransitionMotion";

export const FRAMEWORK_POSITION_TRANSITION =
  "transform 0.52s cubic-bezier(0.16,1,0.3,1)";

export const FRAMEWORK_FADE_TRANSITION = "opacity 0.32s ease";

export const FRAMEWORK_SELECTION_PULSE_DURATION =
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION;
export const FRAMEWORK_DRAWER_CLOSE_DURATION =
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION;
export const FRAMEWORK_DRAWER_OPEN_DURATION =
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION;
export const FRAMEWORK_LABEL_REVEAL_DELAY =
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY;
export const FRAMEWORK_CHROME_REVEAL_DELAY =
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY;
export const FRAMEWORK_REDUCED_MOTION_DRAWER_DURATION =
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION;

export const FRAMEWORK_BREATH_DELAYS = [0, 0.8, 1.5, 2.2, 2.9] as const;

/**
 * Framework Focus Mode needs a slightly longer handoff than the shared
 * overview default because the constellation performs a spatial pull before
 * the reading surface takes over.
 */
export const FRAMEWORK_READING_HANDOFF_DURATION = 660;
export const FRAMEWORK_READING_REDUCED_HANDOFF_DURATION =
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION;
export const FRAMEWORK_RETURN_DURATION =
  ATLAS_OVERVIEW_RETURN_DURATION;
export const FRAMEWORK_RETURN_REDUCED_DURATION =
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION;

export const FRAMEWORK_ATLAS_ENTRY_DURATION =
  ATLAS_SYSTEM_ENTRY_DURATION;
export const FRAMEWORK_ATLAS_EXIT_DURATION =
  ATLAS_SYSTEM_EXIT_DURATION;
export const FRAMEWORK_ATLAS_ACKNOWLEDGE_DELAY =
  ATLAS_SYSTEM_ACKNOWLEDGE_DELAY;
export const FRAMEWORK_ATLAS_RESOLVE_START =
  ATLAS_SYSTEM_RESOLVE_START;
export const FRAMEWORK_ATLAS_RESOLVE_DURATION =
  ATLAS_SYSTEM_RESOLVE_DURATION;
export const FRAMEWORK_ATLAS_PULL_EASE =
  ATLAS_SYSTEM_PULL_EASE;
export const FRAMEWORK_ATLAS_REDUCED_DURATION =
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION;
