import type { MobileReadingSectionData } from "./mobileReadingTypes";

export const GLOBALITY_READING = {
  title: "GLOBALITY",
  subtitle:
    "Redesigning an AI-assisted procurement platform around orientation, work states, and the decisions users needed to make next.",
  sections: [
    {
      id: "context",
      number: "01",
      label: "CONTEXT",
      subtitle:
        "A powerful platform that did not always communicate where users were",
      readingTime: 3,
      paragraphs: [
        "Globality was an AI-assisted procurement platform designed to help enterprise teams create sourcing projects, develop briefs, discover providers, evaluate proposals, and move work toward launch.",
        "The platform already supported a complex procurement journey. The problem was not a lack of capability. It was that users could not always tell where they were, what required attention, or what they should do next.",
        "This was not a new problem.",
        "When I joined the team, I noticed that the logged-in home experience and the project workspace looked structurally similar even though they served very different purposes. Customer-facing teams were hearing the same confusion from users: people could enter a project and lose their sense of whether they were still at the platform level or working inside a specific piece of work.",
        "The problem persisted until a new VP of Design made the navigation experience a priority roughly two years into my time at Globality.",
        "What began as an exploration of navigation patterns exposed something larger.",
        "Global actions, account tools, project-specific destinations, onboarding, and AI assistance were competing inside an experience that did not clearly communicate changes in context.",
        "The navigation existed, but it did not guide.",
        "What initially appeared to be a navigation redesign became a broader effort to rethink how the product oriented users throughout the procurement journey.",
      ],
      insight:
        "The system knew whether someone was browsing the platform or working inside a project. The interface needed to make that distinction just as clear to the user.",
    },
    {
      id: "problem",
      number: "02",
      label: "THE PROBLEM",
      subtitle:
        "Small orientation failures accumulated across a collaborative workflow",
      readingTime: 4,
      paragraphs: [
        "The usability issues were not isolated to a single screen. They appeared across the path from login to active project work.",
        "New users needed a clear place to begin, but the primary create-project action was treated like another navigation item. Returning users needed to scan active work, compare project states, and identify what required attention, but the card-based project view made cross-project comparison difficult.",
        "But procurement introduced another complication. Projects rarely belonged to one person from beginning to end.",
        "A project manager might create an RFP or RFQ. Another team member could review it later. Someone else might add requirements, evaluate providers, or enter the project at another stage entirely. That meant the project could have continuity even when the person entering it did not. Someone could be familiar with procurement—and even with Globality—while still arriving inside a project state they had never seen before.",
        "The homepage and project dashboard did little to resolve that uncertainty. Both relied on similar structures, broad prompts, and persistent AI assistance while giving less emphasis to project state, recent changes, and the actions most likely to move the work forward.",
        "The product contained the information users needed. The difficulty was recognizing what mattered now. Every transition forced users to reconstruct their context:\n\nAm I at the platform level or inside a project? What stage is this project in? What changed since I was last here? Which action should I take next?",
        "This changed how I understood the problem.",
        "The goal was not simply to make navigation easier to use.",
        "The interface needed to orient users before asking them to act.",
      ],
      insight:
        "In collaborative workflows, orientation is continuous. A user may enter an existing project without sharing the context of the people who worked on it before them.",
    },
    {
      id: "approach",
      number: "03",
      label: "APPROACH",
      subtitle:
        "Turning a navigation exploration into an experience architecture",
      readingTime: 5,
      paragraphs: [
        "The initial assignment from the VP of Design was relatively focused:\n\nExplore whether Globality should use a top navigation or a left navigation.",
        "I was the design lead for the initiative, working closely with a PM and Engineering Director through weekly reviews. UX Research supported moderated testing, Customer Success helped surface recurring customer problems, internal procurement users provided domain context, and the evolving vision was reviewed with product and executive leadership.",
        "My role was to synthesize those inputs into the experience direction.",
        "The navigation exploration quickly exposed decisions that extended far beyond navigation.",
        "If we changed how users moved through Globality, we also had to decide what belonged on Home, what belonged inside a project, how new and returning users should enter the experience, how active projects should be represented, where persistent project context should live, and how Glo—the AI assistant—should behave within that system.",
        "I explored both top and left-navigation models.",
        "A compact top navigation created more horizontal workspace during focused work, but its advantages weakened when expanded. The navigation still needed a container large enough to expose deeper destinations, reduced space for Globality and customer branding, and occupied an area I believed should eventually communicate persistent project context.",
        "The left-navigation model stayed closer to existing interaction patterns while preserving the top of the workspace for something more valuable: the active project’s identity, status, and eventual next action.",
        "From there, I mapped the experience around the procurement journey:\n\nCreate a project, develop the brief, match with providers, review providers and proposals, collaborate and decide, award and launch the work.",
        "The exploration ultimately produced a two-level architecture:\n\n• Home-level navigation for creating work, reviewing the portfolio, accessing resources, and managing the account\n\n• In-project navigation for the brief, providers, proposals, collaborators, and project-specific actions",
        "What started as a question about navigation placement became a model for distinguishing managing work from progressing work.",
      ],
      insight:
        "My role was not simply to choose a navigation pattern. It was to define the experience architecture that navigation needed to support.",
    },
    {
      id: "decisions",
      number: "04",
      label: "KEY DECISIONS",
      subtitle: "Designing the interface around the next decision",
      readingTime: 6,
      paragraphs: [
        "Several decisions extended the architecture beyond navigation.",
        "The first was to elevate “Create Project” from a navigation destination into a contextual action on Home. Starting new work should not require users to interpret a menu before they could begin.",
        "The second was to replace project cards with a table.",
        "Returning procurement users often managed several projects simultaneously. They needed to compare stage, ownership, recent activity, status, deadlines, and next steps. A table treated the portfolio as operational work rather than a gallery of individual projects.",
        "The third was to give Home and Project different responsibilities.",
        "Home answered:\n\nWhat work is active? What changed? Where should I resume? How do I start something new?",
        "The Project Dashboard answered:\n\nWhat stage is this project in? What requires attention? Who is involved? What action will move the project forward?",
        "That led to another important decision: persistent project context.",
        "I wanted status and the next action to sit high in the project hierarchy, but the complete vision required several engineering sprints. Rather than replace the direction with an easier short-term solution, the PM and I broke the experience into milestones that could progressively move toward the intended architecture.",
        "That also meant avoiding temporary components when we already knew they would be discarded in a later milestone.",
        "Engineering constraints became part of the design system rather than something addressed after the interface was complete. Legacy decision points had to transition safely into the new architecture. A persistent project title bar consumed additional vertical space on smaller screens. Existing components had to accommodate new positioning. Each decision created consequences elsewhere in the product.",
        "Glo followed the same principle.",
        "The question was no longer simply where the AI assistant should live.",
        "It became:\n\nWhen is AI assistance useful enough to interrupt the user?",
        "Instead of maintaining a large persistent presence, Glo could remain quiet during routine work and surface when context made its assistance useful—after completing a brief, when provider matches became available, or when a stalled decision could be unblocked.",
        "Its value came from timing and context, not constant visibility.",
      ],
      insight:
        "Every surface needed to answer the same question: what does the user need to understand before making the next decision?",
    },
    {
      id: "outcomes",
      number: "05",
      label: "OUTCOMES",
      subtitle: "From usability improvement to a new product standard",
      readingTime: 5,
      paragraphs: [
        "We tested the redesigned experience through moderated usability sessions with approximately 20 new users.",
        "UX Research conducted the sessions while I observed. Participants were first interviewed about their professional responsibilities and familiarity with procurement workflows such as RFPs and RFQs, then asked to perform representative tasks using prototypes I designed and assembled.",
        "The difference was visible in behavior.",
        "New users were able to identify where to begin, distinguish Home from Project, navigate the proposal-creation journey, and recognize the next available action with less searching and hesitation.",
        "For the target proposal-creation task, the redesigned experience produced approximately 40% faster task completion during usability testing.",
        "The table also improved scanning across active work, while the redesigned Project Dashboard gave users stronger orientation around stage, status, collaborators, and next actions.",
        "But the most important outcome was not limited to the test.",
        "The architecture shipped.",
        "The new navigation, Home experience, project portfolio, Project Dashboard, interface hierarchy, and repositioned AI assistant became part of the product.",
        "And once they shipped, they became constraints for what came next.",
        "New product work had to account for the persistent project title layer. Components previously occupying the top-right workspace had to adapt to Glo’s new position. Future features had to consider whether they belonged at the platform or project level and how they behaved across different states of work.",
        "The redesign also influenced the design system. I worked with another designer on the team to establish enough of the new architectural rules and constraints for the system to support subsequent product work.",
        "The redesign did not make procurement less complex.",
        "It gave users—and eventually the organization—a clearer model for deciding which part of that complexity mattered now.",
      ],
      insight:
        "The strongest outcome was not a single screen. The redesign became the product architecture that subsequent work had to build within.",
    },
    {
      id: "lessons",
      number: "06",
      label: "LESSONS",
      subtitle: "What navigation work taught me about orientation",
      readingTime: 4,
      paragraphs: [
        "At the time, I thought I was redesigning navigation.",
        "Looking back, I was designing orientation. Users do not experience enterprise products as a sequence of pages. They experience changing states of work:\n\nEntering, learning, starting, planning, reviewing, deciding, completing and returning.",
        "And in collaborative systems, those states do not necessarily belong to one continuous user journey. People enter work started by others. They return after context has changed. They inherit decisions they did not make. A product becomes easier to use when its structure continuously helps people reconstruct that context. The project gave me a model I continued to use in later work.",
        "Every product should continuously answer five questions:\n\nWhere am I? What changed? What matters now? What can I do next? How do I return?",
        "But Globality taught me something else. Once the architecture shipped, those questions stopped being useful only to designers.",
        "They became constraints for future product decisions.",
        "New features had to establish where they belonged. New components had to respect persistent project context. AI behavior had to respond to the user’s state rather than simply remain visible. The design system had to accommodate the architecture the product had adopted.",
        "A useful design principle can therefore do more than improve an interface. It can give an organization a shared way to decide where future product behavior belongs. The project also changed how I thought about AI assistance.",
        "An intelligent system should not speak merely because it can. It should understand the user’s state, recognize when uncertainty has crossed a meaningful threshold, and offer support without taking over the experience.",
        "That thinking later became part of how I approached presence, context, and spatial continuity in Sovereign Atlas.",
      ],
      insight:
        "Orientation is not a navigation feature. It is a system for preserving enough context that people—and the products supporting them—can make coherent decisions.",
    },
  ] satisfies MobileReadingSectionData[],
} as const;
